### ISSUE TITLE
Bot for Reputation

### ISSUE THREAD

**Issue by aaronkorver** [timothystewart6/BotsPlusPlus#85]
Exalted -- 5000g
Revered -- 1000g
Honored -- 500g
Friendly -- 100g

Any faction

**Comment by aaronkorver** [comment]
Name|  |Expansion
-- | -- | --
Alliance Vanguard |   | Wrath of the Lich King
 Argent Crusade |   | Wrath of the Lich King
 Explorers' League |   | Alliance Vanguard
  Frenzyheart Tribe |   | Sholazar Basin
  Horde Expedition |   | Wrath of the Lich King
  Kirin Tor |   | Wrath of the Lich King
  Knights of the Ebon Blade |   | Wrath of the Lich King
  Sholazar Basin |   | Wrath of the Lich King
   The Ashen Verdict |   | Wrath of the Lich King
   The Frostborn |   | Alliance Vanguard
   The Hand of Vengeance |   | Horde Expedition
   The Kalu'ak |   | Wrath of the Lich King
   The Oracles |   | Sholazar Basin
   The Silver Covenant |   | Alliance Vanguard
   The Sons of Hodir |   | Wrath of the Lich King
   The Sunreavers |   | Horde Expedition
   The Taunka |   | Horde Expedition
   The Wyrmrest Accord |   | Wrath of the Lich King
   Valiance Expedition |   | Alliance Vanguard
   Warsong Offensive|     | Horde Expedition
   Cenarion Expedition |   | The Burning Crusade
   Honor Hold |   | The Burning Crusade
   Keepers of Time |   | The Burning Crusade
   Kurenai |   | The Burning Crusade
   Lower City |   | Shattrath City
   Netherwing |   | The Burning Crusade
   Ogri'la |   | The Burning Crusade
   Sha'tari Skyguard |   | Shattrath City
   Shattered Sun Offensive |   | Shattrath City
   Shattrath City |   | The Burning Crusade
   Sporeggar |   | The Burning Crusade
   The Aldor |   | Shattrath City
   The Consortium |   | The Burning Crusade
   The Mag'har |   | The Burning Crusade
   The Scale of the Sands |   | The Burning Crusade
   The Scryers |   | Shattrath City
   The Sha'tar |   | Shattrath City
   The Violet Eye |   | The Burning Crusade
   Thrallmar |   | The Burning Crusade
   Tranquillien |   | The Burning Crusade
   Alliance |   | Classic
   Alliance Forces |   | Classic
   Argent Dawn |   | Classic
   Bloodsail Buccaneers |   | Classic
   Booty Bay |   | Steamwheedle Cartel
   Brood of Nozdormu |   | Classic
   Cenarion Circle |   | Classic
   Darkmoon Faire |   | Classic
   Darkspear Trolls |   | Horde
   Darnassus |   | Alliance
   Everlook |   | Steamwheedle Cartel
   Exodar |   | Alliance
   Frostwolf Clan |   | Horde Forces
   Gadgetzan |   | Steamwheedle Cartel
   Gelkis Clan Centaur |   | Classic
   Gnomeregan |   | Alliance
   Horde |   | Classic
   Horde Forces |   | Classic
   Hydraxian Waterlords |   | Classic
   Ironforge |   | Alliance
   Magram Clan Centaur |   | Classic
   Orgrimmar |   | Horde
   Ratchet |   | Steamwheedle Cartel
   Ravenholdt |   | Classic
   Shen'dralar |   | Classic
   Silvermoon City |   | Horde
   Silverwing Sentinels |   | Alliance Forces
   Steamwheedle Cartel |   | Classic
   Stormpike Guard |   | Alliance Forces
   Stormwind |   | Alliance
   The Defilers |   | Horde Forces
   The League of Arathor |   | Alliance Forces
   Thorium Brotherhood |   | Classic
   Thunder Bluff |   | Horde
   Timbermaw Hold |   | Classic
   Undercity |   | Horde
   Warsong Outriders |   | Horde Forces
   Zandalar Tribe |   | Classic

**Comment by aaronkorver** [comment]
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130168/Faction  ?

**Comment by timothystewart6** [comment]
Thanks for this!  I am looking into how I can leverage some of the existing items and game mechanics.  I think there might be rep tokens, which I could create a vendor that sells them.   More investigation, but this route might be easier than a flat gold rate in exchange for reputation status.

**Comment by timothystewart6** [comment]
I think it might solve this buy creating an NPC that sells these http://www.wowhead.com/search?q=commendation+badge
